config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :notifications
    end
  end
  resources :microposts, only: [:create, :destroy] do
    member do
      get :reply
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_logged_in_home.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/shared/_logged_in_home.html.haml
.row
  %aside.col-md-4
    %section.user_info
      = render 'shared/user_info'
    %section.micropost_form
      = render 'shared/micropost_form'
  .col-md-8
    %h3 Micropost Feed
    = render 'shared/feed'

app/views/shared/_logged_out_home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/shared/_logged_out_home.html.haml
.center.jumbotron
  %h1 Welcome to the Sample App
  %h2
    This is the home page for the
    %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'

app/views/shared/_micropost_form.html.haml
= form_for(@micropost, html: { multipart: true }) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = hidden_field_tag :reply_to_post_id, ""
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  %span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
:javascript
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.following.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1= current_user.name
%span= link_to "view my profile", current_user
%span= link_to "view my notifications", notifications_user_path(current_user)
%span= pluralize(current_user.microposts.count, "micropost")